// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfnIDGLILdWwFW7Ft0iGCcqCUBLWFxJkY',
    appId: '1:589240596018:web:f107152e2c77ece312ee2b',
    messagingSenderId: '589240596018',
    projectId: 'task-manager-app-d6b4a',
    authDomain: 'task-manager-app-d6b4a.firebaseapp.com',
    storageBucket: 'task-manager-app-d6b4a.firebasestorage.app',
    measurementId: 'G-WFEPT4GG18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlQKPwOceobaXEeQTrboRK0JGUcNUolU',
    appId: '1:589240596018:android:067110a371f005bc12ee2b',
    messagingSenderId: '589240596018',
    projectId: 'task-manager-app-d6b4a',
    storageBucket: 'task-manager-app-d6b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAlZ7iQ9E4MZ1HoHoQn2Tfq0-ocUJVPOo',
    appId: '1:589240596018:ios:8138f91cd057605112ee2b',
    messagingSenderId: '589240596018',
    projectId: 'task-manager-app-d6b4a',
    storageBucket: 'task-manager-app-d6b4a.firebasestorage.app',
    iosBundleId: 'com.gaprah.taskmanager.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAlZ7iQ9E4MZ1HoHoQn2Tfq0-ocUJVPOo',
    appId: '1:589240596018:ios:8138f91cd057605112ee2b',
    messagingSenderId: '589240596018',
    projectId: 'task-manager-app-d6b4a',
    storageBucket: 'task-manager-app-d6b4a.firebasestorage.app',
    iosBundleId: 'com.gaprah.taskmanager.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfnIDGLILdWwFW7Ft0iGCcqCUBLWFxJkY',
    appId: '1:589240596018:web:e2da72560de7b96612ee2b',
    messagingSenderId: '589240596018',
    projectId: 'task-manager-app-d6b4a',
    authDomain: 'task-manager-app-d6b4a.firebaseapp.com',
    storageBucket: 'task-manager-app-d6b4a.firebasestorage.app',
    measurementId: 'G-ZH6SL8B8E0',
  );
}
